### ISSUE TITLE
bug in compile_nyx_mode.sh

### ISSUE THREAD

**Issue by vanhauser-thc** [nyx-fuzz/Nyx#2]
in compile_nyx_mode.sh:
```
if [ ! -f "qemu-nyx/x86_64-softmmu/qemu-system-x86_64" ]; then
        echo "[*] Setting up QEMU-Nyx ..."
    if [ ! -d "qemu-nyx" ]; then
        git clone https://github.com/nyx-fuzz/QEMU-Nyx.git
    fi
    cd QEMU-Nyx/
   ...
```
the check is for qemu-nyx, but the created directory is QEMU-Nyx

in packer/packer/nyx.ini:
```
qemu-pt_path = ../../qemu-nyx/x86_64-softmmu/qemu-system-x86_64
```
which of course fails.
so decide on with uppercase or not ;)

**Comment by schumilo** [comment]
Fixed in [7c18d0173d486da034153c2e771066567b6ee7a4](https://github.com/nyx-fuzz/AFLplusplus-Nyx/commit/7c18d0173d486da034153c2e771066567b6ee7a4).
Thanks!
